### ISSUE TITLE
Object of class common\models\Account could not be converted to int

### ISSUE THREAD

**Issue by dbd5** [yii2tech/balance#10]
Hi @klimov-paul ,

Since today I have been getting this error, not sure why because this worked last week and I haven't changed anything in my Configuration. 
Does anything in this log make sense to you? 
Could you point me in the right direction to debug this?

Thanks

---
1. in /var/www/advanced/vendor/yiisoft/yii2/db/ColumnSchema.php at line 134
   125126127128129130131132133134135136137138139140141142143                if (is_resource($value)) {
                   return $value;
               }
               if (is_float($value)) {
                   // ensure type cast always has . as decimal separator in all locales
                   return str_replace(',', '.', (string) $value);
               }
               return (string) $value;
           case 'integer':
               return (int) $value;
           case 'boolean':
               // treating a 0 bit value as false too
               // https://github.com/yiisoft/yii2/issues/9006
               return (bool) $value && $value !== "\0";
           case 'double':
               return (double) $value;
       }
   
   ```
   return $value;
   ```
2. in /var/www/advanced/vendor/yiisoft/yii2/db/ColumnSchema.php at line 134 – yii\base\ErrorHandler::handleError(8, 'Object of class common\models\Ac...', '/var/www/advanced/vendor/yiisoft...', 134, ...)
3. in /var/www/advanced/vendor/yiisoft/yii2/db/ColumnSchema.php at line 104 – yii\db\ColumnSchema::typecast(common\models\Account)
4. in /var/www/advanced/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php at line 208 – yii\db\ColumnSchema::dbTypecast(common\models\Account)
5. in /var/www/advanced/vendor/yiisoft/yii2/db/Command.php at line 430 – yii\db\mysql\QueryBuilder::insert('{{%ftransaction}}', ['description' => '7165-6729-2589-8850 sent to 0902...', 'type_id' => 3, 'product_id' => 0, 'payment_method_id' => 5, ...], [':qp0' => '7165-6729-2589-8850 sent to 0902...', ':qp1' => 3, ':qp2' => 0, ':qp3' => 5, ...])
6. in /var/www/advanced/vendor/yiisoft/yii2/db/Schema.php at line 450 – yii\db\Command::insert('{{%ftransaction}}', ['description' => '7165-6729-2589-8850 sent to 0902...', 'type_id' => 3, 'product_id' => 0, 'payment_method_id' => 5, ...])

system_log entry

---

exception 'yii\base\ErrorException' with message 'Object of class common\models\Account could not be converted to int' in /var/www/advanced/vendor/yiisoft/yii2/db/ColumnSchema.php:134
Stack trace:
#0 /var/www/advanced/vendor/yiisoft/yii2/db/ColumnSchema.php(134): yii\base\ErrorHandler->handleError(8, 'Object of class...', '/var/www/advanc...', 134, Array)
#1 /var/www/advanced/vendor/yiisoft/yii2/db/ColumnSchema.php(104): yii\db\ColumnSchema->typecast(Object(common\models\Account))
#2 /var/www/advanced/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(208): yii\db\ColumnSchema->dbTypecast(Object(common\models\Account))
#3 /var/www/advanced/vendor/yiisoft/yii2/db/Command.php(430): yii\db\mysql\QueryBuilder->insert('{{%ftransaction...', Array, Array)
#4 /var/www/advanced/vendor/yiisoft/yii2/db/Schema.php(450): yii\db\Command->insert('{{%ftransaction...', Array)
#5 /var/www/advanced/vendor/yii2tech/balance/ManagerDb.php(192): yii\db\Schema->insert('{{%ftransaction...', Array)
#6 /var/www/advanced/vendor/yii2tech/balance/Manager.php(91): yii2tech\balance\ManagerDb->createTransaction(Array)
#7 /var/www/advanced/vendor/yii2tech/balance/ManagerDbTransaction.php(33): yii2tech\balance\Manager->increase(Object(common\models\Account), -5, Array)
#8 /var/www/advanced/vendor/yii2tech/balance/Manager.php(103): yii2tech\balance\ManagerDbTransaction->increase(Object(common\models\Account), -5, Array)
#9 /var/www/advanced/vendor/yii2tech/balance/Manager.php(128): yii2tech\balance\Manager->decrease(Object(common\models\Account), 5, Array)
#10 /var/www/advanced/vendor/yii2tech/balance/ManagerDbTransaction.php(49): yii2tech\balance\Manager->transfer(Object(common\models\Account), 6, 5, Array)
#11 /var/www/advanced/frontend/controllers/SmstextController.php(196): yii2tech\balance\ManagerDbTransaction->transfer(Object(common\models\Account), 6, 5, Array)
#12 [internal function]: frontend\controllers\SmstextController->actionVoucher()
#13 /var/www/advanced/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#14 /var/www/advanced/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/advanced/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('voucher', Array)
#16 /var/www/advanced/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('smstext/voucher', Array)
#17 /var/www/advanced/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /var/www/advanced/frontend/web/index.php(28): yii\base\Application->run()
#19 {main}

**Comment by dbd5** [comment]
Resolved, Nothing to do with the extension - thanks
